# Generated by Django 5.1.5 on 2025-02-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmConnectApp', '0003_usermodel_is_staff_alter_usermodel_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
